main: xyz.reknown.fastercrystals.FasterCrystals
name: $name
version: $version
author: Jyguy
api-version: "$apiVersion"
folia-supported: true
softdepend:
  - DuelsPlugin
  - ProtocolLib
  - ProtocolSupport
  - ViaVersion
  - ViaBackwards
  - ViaRewind
  - Geyser-Spigot
